defaults:
  - _self_

num_envs: 1
freq: 25 # freq needs to be divisible by simulation frequency
camera_follow: True
# env_name: obstacle-dense
env_name: full-warehouse

sensor:
  enable_lidar: True
  enable_camera: True
  color_image: True
  depth_image: True
  semantic_segmentation: True

sim_app:
  anti_aliasing: 0
  width: 1280
  height: 720
  hide_ui: False